# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Browne's home on the Web
email: will.browne@qut.edu.au 
description: The Jekyll version of the Phantom theme by HTML5 UP.
baseurl: "/phantom-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
# logo-image-url: images/logo.svg
# font-awesome-icon-logo:

# Social settings
# github_username: andrewbanchich
# twitter_username: andrewbanchich
# facebook_URL: andrewbanchich
# instagram_username: andrewbanchich
# dribbble_username: andrewbanchich
# 500px_username: andrewbanchich
# phone: 555-5555

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes







plugins:
  - jekyll-relative-links 
relative_links:
  enabled: true
  collections: true

# markdown: kramdown
# kramdown:
#   input: Kramdown

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

# theme: jekyll-theme-minimal
